In [2]:
import json
import requests

In [3]:
geojson_url = 'https://raw.githubusercontent.com/OmdenaAI/laguna-philippines-mapping-fisheries/main/src/data/Results/region_2_results.geojson'
response = requests.get(geojson_url)
geojson_data = response.json()
# print(geojson_data)

In [4]:
features_keep = ["Production Value", "Production Volume", "Commercial Fisheries Volume", "Commercial Fisheries Value", "Marine Municipal Fisheries Volume", "Marine Municipal Fisheries Value", "Inland Municipal Fisheries Volume", "Inland Municipal Fisheries Value", "Aquaculture Volume", "Aquaculture Value"]

In [5]:
features_remove = list(geojson_data["features"][1]["properties"])

In [6]:
for feature in features_keep:
    # Use the "remove()" method to remove the current feature from the list
    features_remove.remove(feature)

In [7]:
for feature in features_remove:
    for i in range(len(geojson_data["features"])):
        geojson_data["features"][i]["properties"].pop(feature, None)

In [8]:
geojson_data["features"][0]["properties"]

{'Production Value': 625.4190563397783,
 'Production Volume': 4.3775153130548405,
 'Commercial Fisheries Volume': 20.47842332240112,
 'Marine Municipal Fisheries Volume': 91.50115688718479,
 'Inland Municipal Fisheries Volume': 45.07783179461188,
 'Aquaculture Volume': 71.69887779509375,
 'Commercial Fisheries Value': 2069.824734533923,
 'Marine Municipal Fisheries Value': 9607.588519170078,
 'Inland Municipal Fisheries Value': 4429.420188572511,
 'Aquaculture Value': 9975.539373269006}

In [9]:
geojson_data["features"][1]["properties"]

{'Production Value': 1268641.315435353,
 'Production Volume': 10885.128816201017,
 'Commercial Fisheries Volume': 1379.5862812419962,
 'Marine Municipal Fisheries Volume': 6164.23143383534,
 'Inland Municipal Fisheries Volume': 3036.794256711806,
 'Aquaculture Volume': 4830.19550037116,
 'Commercial Fisheries Value': 139439.5341566533,
 'Marine Municipal Fisheries Value': 647242.0805153586,
 'Inland Municipal Fisheries Value': 298400.2835475361,
 'Aquaculture Value': 672030.1192473677}

In [10]:
geojson_data["features"][2]["properties"]

{'Production Value': 382267.15843626147,
 'Production Volume': 4035.9397894970457,
 'Commercial Fisheries Volume': 1845.5158143104893,
 'Marine Municipal Fisheries Volume': 8246.085619212838,
 'Inland Municipal Fisheries Volume': 4062.414871597159,
 'Aquaculture Volume': 6461.503932991549,
 'Commercial Fisheries Value': 186532.63585262568,
 'Marine Municipal Fisheries Value': 865836.0202037906,
 'Inland Municipal Fisheries Value': 399179.4132556412,
 'Aquaculture Value': 898995.7566462837}

In [11]:
geojson_data["features"][3]["properties"]

{'Production Value': 24357.40232456731,
 'Production Volume': 252.70922850854535,
 'Commercial Fisheries Volume': 540.9496612027314,
 'Marine Municipal Fisheries Volume': 2417.057164925182,
 'Inland Municipal Fisheries Volume': 1190.7575819264712,
 'Aquaculture Volume': 1893.9682533784226,
 'Commercial Fisheries Value': 54675.64427532677,
 'Marine Municipal Fisheries Value': 253790.1318181621,
 'Inland Municipal Fisheries Value': 117005.75345133031,
 'Aquaculture Value': 263509.77120301354}

In [12]:
geojson_data["features"][4]["properties"]

{'Production Value': 4669.039451703646,
 'Production Volume': 44.18441898297874,
 'Commercial Fisheries Volume': 221.659819922382,
 'Marine Municipal Fisheries Volume': 990.4146251394562,
 'Inland Municipal Fisheries Volume': 487.9254579699512,
 'Aquaculture Volume': 776.0734354637761,
 'Commercial Fisheries Value': 22403.92098086031,
 'Marine Municipal Fisheries Value': 103993.1789435186,
 'Inland Municipal Fisheries Value': 47944.33955691985,
 'Aquaculture Value': 107975.90353006612}

In [13]:
# Save the geojson data to a file
with open('region_2_results_filtered.geojson', 'w') as outfile:
    json.dump(geojson_data, outfile)

In [14]:
filter = ['Isabela', 'Santiago', 'Cagayan', 'Quirino', 'Nueva Vizcaya', 'Batanes']

In [16]:
import pandas as pd
ph_cities = r"C:\Users\patrick\Documents\Omdena\Challenges\Laguna Local Chapter\laguna-philippines-mapping-fisheries\src\data\Cities\ph_cities.csv"
# to dataframe
ph_cities_df = pd.read_csv(ph_cities)

In [17]:
ph_cities_df

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Manila,14.6000,120.9833,Philippines,PH,Manila,primary,23088000.0,1780148.0
1,Quezon City,14.6333,121.0333,Philippines,PH,Quezon,admin,2936116.0,2936116.0
2,Davao,7.0667,125.6000,Philippines,PH,Davao,admin,1632991.0,1632991.0
3,Caloocan City,14.6500,120.9667,Philippines,PH,Caloocan,admin,1583978.0,1583978.0
4,Cebu City,10.3000,123.9000,Philippines,PH,Cebu,admin,922611.0,922611.0
...,...,...,...,...,...,...,...,...,...
1002,Koronadal,6.2541,124.9922,Philippines,PH,South Cotabato,admin,NaN,NaN
1003,San Jose,10.1800,125.5683,Philippines,PH,Dinagat Islands,admin,NaN,NaN
1004,Tabuk,17.4084,121.2785,Philippines,PH,Kalinga,admin,NaN,NaN
1005,Pili,13.7177,123.7448,Philippines,PH,Camarines Sur,admin,NaN,NaN
1006,Madridejos,9.7912,123.3462,Philippines,PH,Cebu,minor,NaN,NaN

In [18]:
# Filter df by admin_name
ph_cities_df = ph_cities_df[ph_cities_df['admin_name'].isin(filter)]

In [20]:
ph_cities_df.reset_index(drop=True, inplace=True)

In [21]:
ph_cities_df

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Tuguegarao,17.6167,121.7167,Philippines,PH,Cagayan,admin,153502.0,153502.0
1,Ilagan,17.1333,121.8833,Philippines,PH,Isabela,admin,145568.0,145568.0
2,Santiago,16.6833,121.5500,Philippines,PH,Santiago,admin,134830.0,134830.0
3,Calabayan,16.7667,121.7833,Philippines,PH,Isabela,NaN,129523.0,129523.0
4,Baggao,17.8894,121.8709,Philippines,PH,Cagayan,NaN,82782.0,82782.0
5,Solana,17.6500,121.6833,Philippines,PH,Cagayan,NaN,82502.0,82502.0
6,Echague,16.7000,121.6500,Philippines,PH,Isabela,NaN,79094.0,79094.0
7,Alicia,16.7787,121.6972,Philippines,PH,Isabela,NaN,71504.0,71504.0
8,Tumauini,17.2667,121.8000,Philippines,PH,Isabela,NaN,67650.0,67650.0
9,Aparri,18.3550,121.6419,Philippines,PH,Cagayan,NaN,65649.0,65649.0
10,San Mateo,16.8833,121.5833,Philippines,PH,Isabela,NaN,64505.0,64505.0
11,Roxas,17.1167,121.6167,Philippines,PH,Isabela,NaN,61773.0,61773.0
12,Tuao,17.7333,121.4500,Philippines,PH,Cagayan,NaN,61535.0,61535.0
13,Bayombong,16.4833,121.1500,Philippines,PH,Nueva Vizcaya,admin,61512.0,61512.0
14,Solano,16.5239,121.1919,Philippines,PH,Nueva Vizcaya,NaN,59517.0,59517.0
15,Gattaran,18.0667,121.6500,Philippines,PH,Cagayan,NaN,56661.0,56661.0
16,San Mariano,16.9833,122.0167,Philippines,PH,Isabela,NaN,55370.0,55370.0
17,Bambang,16.3825,121.1100,Philippines,PH,Nueva Vizcaya,NaN,53433.0,53433.0
18,Ramon,16.7833,121.5333,Philippines,PH,Isabela,NaN,52707.0,52707.0
19,Diffun,16.6000,121.4667,Philippines,PH,Quirino,NaN,52569.0,52569.0
20,Cabagan,17.4333,121.7667,Philippines,PH,Isabela,NaN,50174.0,50174.0
21,Peñablanca,17.6333,121.7833,Philippines,PH,Cagayan,NaN,48584.0,48584.0
22,Amulung,17.8387,121.7235,Philippines,PH,Cagayan,NaN,47860.0,47860.0
23,Jones,16.5583,121.7000,Philippines,PH,Isabela,NaN,45666.0,45666.0
24,Lal-lo,18.2000,121.6667,Philippines,PH,Cagayan,NaN,44506.0,44506.0
25,Angadanan,16.7571,121.7479,Philippines,PH,Isabela,NaN,43061.0,43061.0
26,Cordon,16.6667,121.4500,Philippines,PH,Isabela,NaN,42926.0,42926.0
27,Cabatuan,16.9589,121.6692,Philippines,PH,Isabela,NaN,39413.0,39413.0
28,Lasam,18.0667,121.6000,Philippines,PH,Cagayan,NaN,39135.0,39135.0
29,Gonzaga,18.2667,122.0000,Philippines,PH,Cagayan,NaN,38892.0,38892.0
30,Alcala,17.9031,121.6590,Philippines,PH,Cagayan,NaN,38883.0,38883.0
31,Maddela,16.3500,121.7000,Philippines,PH,Quirino,NaN,38499.0,38499.0
32,Kasibu,16.3167,121.2833,Philippines,PH,Nueva Vizcaya,NaN,37705.0,37705.0
33,Aritao,16.2973,121.0338,Philippines,PH,Nueva Vizcaya,NaN,37225.0,37225.0
34,Enrile,17.5500,121.7000,Philippines,PH,Cagayan,NaN,35834.0,35834.0
35,Bagabag,16.6044,121.2521,Philippines,PH,Nueva Vizcaya,NaN,35501.0,35501.0
36,Aurora,16.9918,121.6357,Philippines,PH,Isabela,NaN,35017.0,35017.0
37,Ballesteros,18.4000,121.5167,Philippines,PH,Cagayan,NaN,34299.0,34299.0
38,Allacapan,18.2270,121.5556,Philippines,PH,Cagayan,NaN,33571.0,33571.0
39,Santa Ana,18.4667,122.1500,Philippines,PH,Cagayan,NaN,32906.0,32906.0
40,Abulug,18.4441,121.4576,Philippines,PH,Cagayan,NaN,32497.0,32497.0
41,Naguilian,17.0167,121.8500,Philippines,PH,Isabela,NaN,31902.0,31902.0
42,San Manuel,17.0167,121.6333,Philippines,PH,Isabela,NaN,31896.0,31896.0
43,Cabarroguis,16.5833,121.5000,Philippines,PH,Quirino,admin,30582.0,30582.0
44,Mallig,17.2000,121.6167,Philippines,PH,Isabela,NaN,30459.0,30459.0
45,Buguey,18.2882,121.8331,Philippines,PH,Cagayan,minor,30175.0,30175.0
46,Claveria,18.6000,121.0833,Philippines,PH,Cagayan,NaN,29921.0,29921.0
47,Gamu,17.0500,121.8333,Philippines,PH,Isabela,NaN,29904.0,29904.0
48,Benito Soliven,16.9833,121.9500,Philippines,PH,Isabela,NaN,29624.0,29624.0
49,Iguig,17.7500,121.7333,Philippines,PH,Cagayan,NaN,27862.0,27862.0
50,Aglipay,16.4889,121.5874,Philippines,PH,Quirino,NaN,27787.0,27787.0
51,Dupax Del Norte,16.2864,121.0942,Philippines,PH,Nueva Vizcaya,NaN,27514.0,27514.0
52,Basco,20.4500,121.9667,Philippines,PH,Batanes,admin,8579.0,8579.0

In [22]:
# Save to csv
ph_cities_df.to_csv('ph_cities_filtered.csv', index=False)