In [1]:
import json
import requests

In [66]:
geojson_url = 'https://raw.githubusercontent.com/OmdenaAI/laguna-philippines-mapping-fisheries/main/src/data/Results/region2_results_gdf_with_forecast_and_recommendation.geojson'
response = requests.get(geojson_url)
geojson_data = response.json()
# print(geojson_data)

In [46]:
geojson_data

{'type': 'FeatureCollection',
 'crs': {'type': 'name',
  'properties': {'name': 'urn:ogc:def:crs:EPSG::32651'}},
 'features': [{'type': 'Feature',
   'properties': {'index': 'Batanes',
    'population': 18831,
    'lit_per_area': 51.17089305251264,
    'mean_temperature': 24.891143058387968,
    'Recommended Production Value (2015)': '52887.96542152914',
    'Recommended Production Value (2016)': '45116.86578316639',
    'Recommended Production Value (2017)': '49718.24285008906',
    'Recommended Production Value (2018)': '52169.74737838565',
    'Recommended Production Value (2019)': '54493.36444338271',
    'Recommended Production Value (2020)': '61483.46756857678',
    'Recommended Production Value (2021) - Forecasted': '55358.66909992549',
    'Recommended Production Value (2022) - Forecasted': '57819.77026871876',
    'Recommended Production Volume (2015)': '507.3308024884554',
    'Recommended Production Volume (2016)': '408.3739726271816',
    'Recommended Production Volume (2017)': '442.0610834727589',
    'Recommended Production Volume (2018)': '441.4784526604602',
    'Recommended Production Volume (2019)': '446.5965629857388',
    'Recommended Production Volume (2020)': '430.3431723943733',
    'Recommended Production Volume (2021) - Forecasted': '419.4947527254336',
    'Recommended Production Volume (2022) - Forecasted': '410.8827284905328',
    'Recommendation': 'Decrease Fishing Activity (Keep Price)'},
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [[[[121.8857917670001, 20.28998973400007],
       [121.885594326, 20.28985198800007],
       [121.885503221, 20.28964064700006],
       [121.8855488160001, 20.28945496100005],
       [121.885672902, 20.28918666100003],
       [121.8858197520001, 20.28905133400008],
       [121.8857868900001, 20.28871415400005],
       [121.885921078, 20.28860969400006],
       [121.8859413500001, 20.28847709600007],
       [121.886121105, 20.28836076800008],
       [121.8862654070001, 20.28833704200002],
       [121.88618695, 20.28819218900003],
       [121.8863515050001, 20.28815659200006],
       [121.8864249310001, 20.28807824400008],
       [121.8863540640001, 20.28796900800006],
       [121.886176844, 20.28804971800002],
       [121.8859566020001, 20.28803306900005],
       [121.8858325450001, 20.28812090900004],
       [121.885640166, 20.28800453400004],
       [121.8854756170001, 20.28800688700005],
       [121.885311053, 20.28809947000008],
       [121.8850581, 20.28801312700006],
       [121.885075796, 20.28818646700006],
       [121.884941624, 20.28818644900002],
       [121.884774522, 20.28831939900004],
       [121.8846985590001, 20.28843098800007],
       [121.884409977, 20.28833834400007],
       [121.884235319, 20.28822434400007],
       [121.8841290170001, 20.28807948600007],
       [121.8840556330001, 20.28788002000005],
       [121.8838733880001, 20.28773040200002],
       [121.8838734030001, 20.28764017200007],
       [121.88373674, 20.28738721400003],
       [121.883719076, 20.28702866500004],
       [121.8837545480001, 20.28683871200008],
       [121.8838153200001, 20.28674374100007],
       [121.8840507470001, 20.28676277000005],
       [121.8841849280001, 20.28669392800003],
       [121.884288704, 20.28678892200003],
       [121.8846723350001, 20.28679352800003],
       [121.8846393330001, 20.28641727100006],
       [121.8844365680001, 20.28637176200004],
       [121.884125838, 20.28612570800004],
       [121.884240481, 20.28591092800008],
       [121.8841192900001, 20.28571658300007],
       [121.8840157090001, 20.28566281800005],
       [121.8837975490001, 20.28542504700005],
       [121.883500323, 20.28506204700005],
       [121.8835124220001, 20.28491774400004],
       [121.883289847, 20.28472751900006],
       [121.8833317560001, 20.28452699400003],
       [121.8828975920001, 20.28437395000003],
       [121.8828865200001, 20.28468818200002],
       [121.8830452240001, 20.28458690600007],
       [121.883115747, 20.28461792700006],
       [121.8830822220001, 20.28499475800004],
       [121.8825113480001, 20.28519313800007],
       [121.88236368, 20.28518278000007],
       [121.882339416, 20.28530888300003],
       [121.8821124000001, 20.28532125300006],
       [121.881951799, 20.28523651500007],
       [121.8820179610001, 20.28499051400007],
       [121.8818196570001, 20.28466178000002],
       [121.8816808170001, 20.28458733500003],
       [121.881402167, 20.28456373300003],
       [121.8812743230001, 20.28462159800006],
       [121.8811288640001, 20.28459263200006],
       [121.8810825600001, 20.28470632800003],
       [121.8809260960001, 20.28458639900003],
       [121.8805679540001, 20.28444870100003],
       [121.8801090650001, 20.28436382900003],
       [121.8800563200001, 20.28440386500006],
       [121.8797022220001, 20.28443914000007],
       [121.8794275390001, 20.28474054100008],
       [121.8793403180001, 20.28476678400006],
       [121.8791378960001, 20.28461860000004],
       [121.8788515450001, 20.28460625600007],
       [121.878479466, 20.28449782500007],
       [121.87830368, 20.28447188400003],
       [121.8782232970001, 20.28458729200003],
       [121.8779772070001, 20.28449773800003],
       [121.8778272440001, 20.28440312100003],
       [121.8776898560001, 20.28437503600003],
       [121.8774675400001, 20.28446473400004],
       [121.877284228, 20.28440110200006],
       [121.877213931, 20.28430451200006],
       [121.8770481920001, 20.28427386000004],
       [121.8769452460001, 20.28418668600006],
       [121.8766735200001, 20.28415695500007],
       [121.8761909010001, 20.284152],
       [121.8760165230001, 20.28419660900005],
       [121.8756254960001, 20.28415034800003],
       [121.8753824260001, 20.28404295800004],
       [121.8751622520001, 20.28404130400003],
       [121.8748584420001, 20.28424587400008],
       [121.8747582530001, 20.28427717800002],
       [121.8746862840001, 20.28447474100005],
       [121.8745449810001, 20.28457109300007],
       [121.8742958070001, 20.28457827300002],
       [121.8741905090001, 20.28447705500002],
       [121.873946777, 20.28453370100004],
       [121.873345295, 20.28433036300004],
       [121.8730062310001, 20.28426524000002],
       [121.8723958920001, 20.28412039600005],
       [121.8720619760001, 20.28401672100006],
       [121.871656442, 20.28382479900006],
       [121.870689082, 20.28325490300006],
       [121.870355708, 20.28300665700004],
       [121.8700493150001, 20.28270916000002],
       [121.8698438810001, 20.28244403500003],
       [121.8695922390001, 20.28206693200008],
       [121.8694132590001, 20.28161136400007],
       [121.8693821730001, 20.28126956300002],
       [121.8693171850001, 20.28113893400007],
       [121.8693079010001, 20.28099263300004],
       [121.86937846, 20.28090903000003],
       [121.8696198450001, 20.28084981200004],
       [121.8697164, 20.28086548800007],
       [121.8697942350001, 20.28075934300006],
       [121.8700653670001, 20.28076592300005],
       [121.8702577240001, 20.28070944800004],
       [121.8703458020001, 20.28063773400004],
       [121.87047094, 20.28063776100004],
       [121.8703736640001, 20.28041819500004],
       [121.870227676, 20.28039425200006],
       [121.8699574840001, 20.28041201700006],
       [121.869904213, 20.28029679800005],
       [121.869672431, 20.28046847100006],
       [121.869415224, 20.28037929200008],
       [121.8693539000001, 20.28048824700005],
       [121.869149213, 20.28037670400005],
       [121.86904485, 20.28038030300007],
       [121.8688732180001, 20.28013042700007],
       [121.868710339, 20.28008290100007],
       [121.868595858, 20.28015307700002],
       [121.8684197570001, 20.28016542600005],
       [121.868175896, 20.27998400800004],
       [121.8678238240001, 20.27950902900005],
       [121.8674020750001, 20.27911947500007],
       [121.867045371, 20.27863410000003],
       [121.8668627110001, 20.27848952300008],
       [121.8668209110001, 20.27840072800007],
       [121.8665370980001, 20.27828552900007],
       [121.8663302220001, 20.27814714000004],
       [121.8657317640001, 20.27758236700004],
       [121.865625399, 20.27745945300006],
       [121.8654977470001, 20.27739954400005],
       [121.8653921590001, 20.27714968100003],
       [121.8656981890001, 20.27691230700003],
       [121.8656894070001, 20.27683177800003],
       [121.865801699, 20.27671617800007],
       [121.8657004790001, 20.27658814800003],
       [121.8657379210001, 20.27651176100005],
       [121.865905191, 20.27658406800003],
       [121.8659844480001, 20.27652627300006],
       [121.8659008740001, 20.27627228600005],
       [121.8657974450001, 20.27617521700006],
       [121.865663183, 20.27614214800008],
       [121.8653703900001, 20.27627215900003],
       [121.865134193, 20.27622636200005],
       [121.864955826, 20.27647409100007],
       [121.864814936, 20.27652980400006],
       [121.8645574110001, 20.27648225000007],
       [121.864280128, 20.27625299100004],
       [121.864198729, 20.27609604800006],
       [121.8638592680001, 20.27579742500006],
       [121.8635909560001, 20.27541047900007],
       [121.8635205620001, 20.27525560200007],
       [121.863096517, 20.27455722300004],
       [121.8629350340001, 20.27431230000008],
       [121.8628019380001, 20.27417781300005],
       [121.8626677330001, 20.27395684700002],
       [121.8626237630001, 20.27378339500007],
       [121.8625247240001, 20.27374207400004],
       [121.8623817180001, 20.27351078200007],
       [121.8623631920001, 20.27328647100006],
       [121.8622949740001, 20.27322244500004],
       [121.8623786530001, 20.27310477500004],
       [121.8623171080001, 20.27280949700003],
       [121.862044177, 20.27278877700007],
       [121.8619693110001, 20.27288167200004],
       [121.861786656, 20.27275154400007],
       [121.8616127780001, 20.27256872300006],
       [121.8614631680001, 20.27235188300006],
       [121.8613113330001, 20.27221350100007],
       [121.8612299590001, 20.27199299800003],
       [121.8610209650001, 20.27162954300007],
       [121.860891258, 20.27111384300002],
       [121.860851772, 20.27067619700006],
       [121.8609685440001, 20.27030250500007],
       [121.861129247, 20.27022821600008],
       [121.8611424840001, 20.27012704600003],
       [121.861299904, 20.26995823900006],
       [121.861344849, 20.26978278700005],
       [121.8616484950001, 20.26943288600006],
       [121.8617059540001, 20.26910770600006],
       [121.8618032610001, 20.26896736000003],
       [121.86182897, 20.26881765100006],
       [121.8620379710001, 20.26863783900006],
       [121.8621855580001, 20.26831504100005],
       [121.862146262, 20.26819973200003],
       [121.8623282360001, 20.26797148700007],
       [121.862430172, 20.26795686200006],
       [121.8624548240001, 20.26771704600003],
       [121.8625876420001, 20.26746111700004],
       [121.862746452, 20.26743609400006],
       [121.8628473220001, 20.26714787200007],
       [121.8629776070001, 20.26714098800005],
       [121.8629456870001, 20.26701645800006],
       [121.8631252050001, 20.26677437500007],
       [121.8632695590001, 20.26641413000004],
       [121.8634663040001, 20.26609134300003],
       [121.8634737210001, 20.26595068000006],
       [121.8636674530001, 20.26566406700005],
       [121.8637412630001, 20.26543579300005],
       [121.863849457, 20.26531360300004],
       [121.8640510350001, 20.26527676000006],
       [121.8640584330001, 20.26519143900003],
       [121.8642157640001, 20.26515458300003],
       [121.8641793390001, 20.26499430900003],
       [121.8643268830001, 20.26480294800007],
       [121.8644866870001, 20.26471305500007],
       [121.8644719700001, 20.26460236400004],
       [121.864550653, 20.26452398000004],
       [121.8647055120001, 20.26453554900007],
       [121.8648702300001, 20.26445026800008],
       [121.8649144980001, 20.26437418200004],
       [121.865140696, 20.26420128500007],
       [121.8652882490001, 20.26396611100006],
       [121.8653251540001, 20.26384851600005],
       [121.8654529700001, 20.26387160700006],
       [121.8656102140001, 20.26413913800008],
       [121.8657109870001, 20.26418067000003],
       [121.865848686, 20.26401928500007],
       [121.8660035290001, 20.26408389000005],
       [121.8661313870001, 20.26395939700006],
       [121.8660356090001, 20.26363423100003],
       [121.8658733880001, 20.26358115400006],
       [121.8655134180001, 20.26359430100007],
       [121.8655701780001, 20.26342019700007],
       [121.8656423680001, 20.26338635800005],
       [121.8658796100001, 20.26308896500007],
       [121.865956986, 20.26294146700008],
       [121.8658663210001, 20.26283948100007],
       [121.865696196, 20.26279591000002],
       [121.865562217, 20.26254679200002],
       [121.8658303340001, 20.26245980000004],
       [121.8658870620001, 20.26240661000003],
       [121.8658484460001, 20.26222039100003],
       [121.865688649, 20.26211636600004],
       [121.865559759, 20.26211149800002],
       [121.865510835, 20.26191802200003],
       [121.8653742040001, 20.26193975400003],
       [121.865268483, 20.26204855100008],
       [121.865178204, 20.26224441100004],
       [121.864847767, 20.26221168400002],
       [121.864749767, 20.26236401200003],
       [121.8646002700001, 20.26230593600008],
       [121.8645435290001, 20.26240749100003],
       [121.8645615280001, 20.26256952100005],
       [121.864486714, 20.26277264000004],
       [121.8644197000001, 20.26273876700003],
       [121.8643811060001, 20.26247999900005],
       [121.864406913, 20.26237601800005],
       [121.8642678150001, 20.26200840200005],
       [121.864180193, 20.26192857700005],
       [121.8640668260001, 20.26172782900005],
       [121.8638731030001, 20.26159034500006],
       [121.8636926580001, 20.26157820900005],
       [121.8635921020001, 20.26165556800004],
       [121.863486423, 20.26161684800007],
       [121.863156426, 20.26174493300005],
       [121.8630894700001, 20.26151759600003],
       [121.86332413, 20.26124206100008],
       [121.863306133, 20.26107519400006],
       [121.8634325070001, 20.26086483400007],
       [121.863205697, 20.26074386300007],
       [121.8630846140001, 20.26076559400008],
       [121.8629763130001, 20.26087439000003],
       [121.8628267890001, 20.26091304400006],
       [121.8626772240001, 20.26109196000004],
       [121.8625792800001, 20.26104840500005],
       [121.8626721280001, 20.26089124000003],
       [121.8628113680001, 20.26075826900006],
       [121.86284234, 20.26062527200003],
       [121.862618063, 20.26065906900004],
       [121.86221072, 20.26082582500004],
       [121.8621746590001, 20.26073392100005],
       [121.86196841, 20.26082092500008],
       [121.8618034360001, 20.26080153500004],
       [121.8616935340001, 20.26057883600004],
       [121.861484743, 20.26054492400004],
       [121.8614512690001, 20.26042158200005],
       [121.860987288, 20.26035374600008],
       [121.8609820490001, 20.26062459400003],
       [121.860907235, 20.26081320100008],
       [121.860829874, 20.26089782000003],
       [121.86082982, 20.26107677400006],
       [121.860657088, 20.26113960300006],
       [121.8606597150001, 20.26097757800005],
       [121.860515436, 20.26072603600005],
       [121.8604447450001, 20.26067749000003],
       [121.860202412, 20.26073546300006],
       [121.860122452, 20.26089021300004],
       [121.860135309, 20.26099420300005],
       [121.859983197, 20.26106187400006],
       [121.8596636100001, 20.26086832200008],
       [121.8594831360001, 20.26095774900006],
       [121.8594522500001, 20.26080538700006],
       [121.8591487370001, 20.26077065400005],
       [121.8590687840001, 20.26089880200004],
       [121.8589321870001, 20.26081170400005],
       [121.8588213380001, 20.26082134600006],
       [121.8587595480001, 20.26057949900007],
       [121.8587647610001, 20.26040054600003],
       [121.8585482650001, 20.26028199000007],
       [121.8584683280001, 20.26035935200002],
       [121.8586074890001, 20.26048514200005],
       [121.858566192, 20.26064473800005],
       [121.858434684, 20.26077045200003],
       [121.858135614, 20.26091062800003],
       [121.8578091300001, 20.26097749100006],
       [121.8578658070001, 20.26108391300005],
       [121.857765233, 20.26120479900004],
       [121.8575616100001, 20.26112735500004],
       [121.8574121350001, 20.26101607000004],
       [121.8572908260001, 20.26147551100007],
       [121.8572050770001, 20.26170004600004],
       [121.8570678640001, 20.26169578600008],
       [121.8570341630001, 20.26157338300004],
       [121.856921712, 20.26151426400003],
       [121.8568947590001, 20.26139397300005],
       [121.8567665210001, 20.26145935300008],
       [121.856896942, 20.26159444500007],
       [121.8568811490001, 20.26173582600006],
       [121.856737446, 20.26181224400005],
       [121.8568138210001, 20.26212246800003],
       [121.8569217480001, 20.26226388500004],
       [121.8566855160001, 20.26239042900005],
       [121.856489794, 20.26245789800004],
       [121.8564583330001, 20.26236292900006],
       [121.8561142840001, 20.26202941200006],
       [121.855997332, 20.26197451200005],
       [121.855785835, 20.26212849600006],
       [121.855963458, 20.26233095700007],
       [121.8560196450001, 20.26247236000006],
       [121.855882412, 20.26252718300003],
       [121.8559678030001, 20.26278465600006],
       [121.8558845380001, 20.26289014200006],
       [121.8557203460001, 20.26284155800005],
       [121.8556754110001, 20.26268538800002],
       [121.8555089690001, 20.26263891300005],
       [121.85553585, 20.26296600600006],
       [121.8553955580001, 20.26311755800003],
       [121.8554900170001, 20.26316823200006],
       [121.8555821800001, 20.26335606900005],
       [121.855363975, 20.26338554700004],
       [121.855269569, 20.26317871800006],
       [121.8551728020001, 20.26329475000006],
       [121.8552717370001, 20.26341506200004],
       [121.855059026, 20.26367332000007],
       [121.855002731, 20.26384634100003],
       [121.854908234, 20.26390539900007],
       [121.8547641930001, 20.26412481700004],
       [121.8547685850001, 20.26443502100005],
       [121.85482704, 20.26452390900005],
       [121.8545794910001, 20.26483614700004],
       [121.8546447000001, 20.26491002400007],
       [121.8545096940001, 20.26501971500005],
       [121.854642332, 20.26525187900006],
       [121.854556395, 20.26546713200003],
       [121.854299865, 20.26572661100005],
       [121.85418287, 20.26579199200006],
       [121.8539263380001, 20.26605358000006],
       [121.8537145940001, 20.26617857700006],
       [121.8535301210001, 20.26621861400002],
       [121.8533816730001, 20.26616792200002],
       [121.8530779680001, 20.26623746500007],
       [121.8530149960001, 20.26620157100007],
       [121.852631477, 20.26619890500007],
       [121.8524920210001, 20.26616931800004],
       [121.8524223200001, 20.26607433500004],
       [121.8522221070001, 20.26610170500004],
       [121.8521299180001, 20.26599194400006],
       [121.8520331420001, 20.26612274700005],
       [121.8520915250001, 20.26641186600006],
       [121.8519700370001, 20.26645614100005],
       [121.851988674, 20.26659228200003],
       [121.851966077, 20.26687715500003],
       [121.8518625710001, 20.26695520000004],
       [121.851526151, 20.26704878300006],
       [121.8515193740001, 20.26712685900003],
       [121.851373122, 20.26722177200003],
       [121.8512651450001, 20.26722384700003],
       [121.8511278540001, 20.26741794300005],
       [121.8510872830001, 20.26763543000004],
       [121.851141223, 20.26776417100007],
       [121.851062379, 20.26806585200006],
       [121.85119278, 20.26825581400004],
       [121.8512197020001, 20.26845228800005],
       [121.851298356, 20.26866755600003],
       [121.8515142130001, 20.26892929300004],
       [121.8514736970001, 20.26899469700004],
       [121.8511969850001, 20.26905158300008],
       [121.8510013360001, 20.26889325400003],
       [121.850783155, 20.26883198500008],

In [70]:
features_keep = ["index","Recommendation", "Recommended Production Value (2022) - Forecasted", "Recommended Production Volume (2022) - Forecasted"]

In [48]:
list(geojson_data["features"][0]['properties'])

['index',
 'population',
 'lit_per_area',
 'mean_temperature',
 'Recommended Production Value (2015)',
 'Recommended Production Value (2016)',
 'Recommended Production Value (2017)',
 'Recommended Production Value (2018)',
 'Recommended Production Value (2019)',
 'Recommended Production Value (2020)',
 'Recommended Production Value (2021) - Forecasted',
 'Recommended Production Value (2022) - Forecasted',
 'Recommended Production Volume (2015)',
 'Recommended Production Volume (2016)',
 'Recommended Production Volume (2017)',
 'Recommended Production Volume (2018)',
 'Recommended Production Volume (2019)',
 'Recommended Production Volume (2020)',
 'Recommended Production Volume (2021) - Forecasted',
 'Recommended Production Volume (2022) - Forecasted',
 'Recommendation']

In [71]:
features_remove = list(geojson_data["features"][0]['properties'])

In [72]:
for feature in features_keep:
    features_remove.remove(feature)

In [73]:
for feature in features_remove:
    for i in range(len(geojson_data["features"])):
        geojson_data["features"][i]["properties"].pop(feature, None)

In [74]:
geojson_data["features"][0]["properties"]

{'index': 'Batanes',
 'Recommended Production Value (2022) - Forecasted': '57819.77026871876',
 'Recommended Production Volume (2022) - Forecasted': '410.8827284905328',
 'Recommendation': 'Decrease Fishing Activity (Keep Price)'}

In [75]:
# Save the geojson data to a file
with open('region_2_results_with_recommendation.geojson', 'w') as outfile:
    json.dump(geojson_data, outfile)

In [14]:
filter = ['Isabela', 'Santiago', 'Cagayan', 'Quirino', 'Nueva Vizcaya', 'Batanes']

In [55]:
import geopandas as gpd
df = gpd.read_file('region_2_results_with_recommendation.geojson')
df

,Recommended Production Value (2022) - Forecasted,Recommended Production Volume (2022) - Forecasted,Recommendation,geometry
0,57819.77026871876,410.8827284905328,Decrease Fishing Activity (Keep Price),"MULTIPOLYGON (((121.886 20.290, 121.886 20.290..."
1,3598858.320985314,27149.11753017213,Decrease Fishing Activity,"MULTIPOLYGON (((121.600 17.548, 121.577 17.555..."
2,983951.5570860102,10405.51968336106,Decrease Fishing Activity,"MULTIPOLYGON (((121.576 16.594, 121.576 16.598..."
3,43964.31857073197,464.6858453632383,Increase Fishing Activity,"POLYGON ((120.827 16.176, 120.815 16.181, 120...."
4,45823.3591622723,410.4131402819991,Increase Fishing Activity,"POLYGON ((121.511 15.950, 121.505 15.949, 121...."

In [16]:
import pandas as pd
ph_cities = r"C:\Users\patrick\Documents\Omdena\Challenges\Laguna Local Chapter\laguna-philippines-mapping-fisheries\src\data\Cities\ph_cities.csv"
# to dataframe
ph_cities_df = pd.read_csv(ph_cities)

In [17]:
ph_cities_df

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Manila,14.6000,120.9833,Philippines,PH,Manila,primary,23088000.0,1780148.0
1,Quezon City,14.6333,121.0333,Philippines,PH,Quezon,admin,2936116.0,2936116.0
2,Davao,7.0667,125.6000,Philippines,PH,Davao,admin,1632991.0,1632991.0
3,Caloocan City,14.6500,120.9667,Philippines,PH,Caloocan,admin,1583978.0,1583978.0
4,Cebu City,10.3000,123.9000,Philippines,PH,Cebu,admin,922611.0,922611.0
...,...,...,...,...,...,...,...,...,...
1002,Koronadal,6.2541,124.9922,Philippines,PH,South Cotabato,admin,NaN,NaN
1003,San Jose,10.1800,125.5683,Philippines,PH,Dinagat Islands,admin,NaN,NaN
1004,Tabuk,17.4084,121.2785,Philippines,PH,Kalinga,admin,NaN,NaN
1005,Pili,13.7177,123.7448,Philippines,PH,Camarines Sur,admin,NaN,NaN
1006,Madridejos,9.7912,123.3462,Philippines,PH,Cebu,minor,NaN,NaN

In [18]:
# Filter df by admin_name
ph_cities_df = ph_cities_df[ph_cities_df['admin_name'].isin(filter)]

In [20]:
ph_cities_df.reset_index(drop=True, inplace=True)

In [21]:
ph_cities_df

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Tuguegarao,17.6167,121.7167,Philippines,PH,Cagayan,admin,153502.0,153502.0
1,Ilagan,17.1333,121.8833,Philippines,PH,Isabela,admin,145568.0,145568.0
2,Santiago,16.6833,121.5500,Philippines,PH,Santiago,admin,134830.0,134830.0
3,Calabayan,16.7667,121.7833,Philippines,PH,Isabela,NaN,129523.0,129523.0
4,Baggao,17.8894,121.8709,Philippines,PH,Cagayan,NaN,82782.0,82782.0
5,Solana,17.6500,121.6833,Philippines,PH,Cagayan,NaN,82502.0,82502.0
6,Echague,16.7000,121.6500,Philippines,PH,Isabela,NaN,79094.0,79094.0
7,Alicia,16.7787,121.6972,Philippines,PH,Isabela,NaN,71504.0,71504.0
8,Tumauini,17.2667,121.8000,Philippines,PH,Isabela,NaN,67650.0,67650.0
9,Aparri,18.3550,121.6419,Philippines,PH,Cagayan,NaN,65649.0,65649.0
10,San Mateo,16.8833,121.5833,Philippines,PH,Isabela,NaN,64505.0,64505.0
11,Roxas,17.1167,121.6167,Philippines,PH,Isabela,NaN,61773.0,61773.0
12,Tuao,17.7333,121.4500,Philippines,PH,Cagayan,NaN,61535.0,61535.0
13,Bayombong,16.4833,121.1500,Philippines,PH,Nueva Vizcaya,admin,61512.0,61512.0
14,Solano,16.5239,121.1919,Philippines,PH,Nueva Vizcaya,NaN,59517.0,59517.0
15,Gattaran,18.0667,121.6500,Philippines,PH,Cagayan,NaN,56661.0,56661.0
16,San Mariano,16.9833,122.0167,Philippines,PH,Isabela,NaN,55370.0,55370.0
17,Bambang,16.3825,121.1100,Philippines,PH,Nueva Vizcaya,NaN,53433.0,53433.0
18,Ramon,16.7833,121.5333,Philippines,PH,Isabela,NaN,52707.0,52707.0
19,Diffun,16.6000,121.4667,Philippines,PH,Quirino,NaN,52569.0,52569.0
20,Cabagan,17.4333,121.7667,Philippines,PH,Isabela,NaN,50174.0,50174.0
21,Peñablanca,17.6333,121.7833,Philippines,PH,Cagayan,NaN,48584.0,48584.0
22,Amulung,17.8387,121.7235,Philippines,PH,Cagayan,NaN,47860.0,47860.0
23,Jones,16.5583,121.7000,Philippines,PH,Isabela,NaN,45666.0,45666.0
24,Lal-lo,18.2000,121.6667,Philippines,PH,Cagayan,NaN,44506.0,44506.0
25,Angadanan,16.7571,121.7479,Philippines,PH,Isabela,NaN,43061.0,43061.0
26,Cordon,16.6667,121.4500,Philippines,PH,Isabela,NaN,42926.0,42926.0
27,Cabatuan,16.9589,121.6692,Philippines,PH,Isabela,NaN,39413.0,39413.0
28,Lasam,18.0667,121.6000,Philippines,PH,Cagayan,NaN,39135.0,39135.0
29,Gonzaga,18.2667,122.0000,Philippines,PH,Cagayan,NaN,38892.0,38892.0
30,Alcala,17.9031,121.6590,Philippines,PH,Cagayan,NaN,38883.0,38883.0
31,Maddela,16.3500,121.7000,Philippines,PH,Quirino,NaN,38499.0,38499.0
32,Kasibu,16.3167,121.2833,Philippines,PH,Nueva Vizcaya,NaN,37705.0,37705.0
33,Aritao,16.2973,121.0338,Philippines,PH,Nueva Vizcaya,NaN,37225.0,37225.0
34,Enrile,17.5500,121.7000,Philippines,PH,Cagayan,NaN,35834.0,35834.0
35,Bagabag,16.6044,121.2521,Philippines,PH,Nueva Vizcaya,NaN,35501.0,35501.0
36,Aurora,16.9918,121.6357,Philippines,PH,Isabela,NaN,35017.0,35017.0
37,Ballesteros,18.4000,121.5167,Philippines,PH,Cagayan,NaN,34299.0,34299.0
38,Allacapan,18.2270,121.5556,Philippines,PH,Cagayan,NaN,33571.0,33571.0
39,Santa Ana,18.4667,122.1500,Philippines,PH,Cagayan,NaN,32906.0,32906.0
40,Abulug,18.4441,121.4576,Philippines,PH,Cagayan,NaN,32497.0,32497.0
41,Naguilian,17.0167,121.8500,Philippines,PH,Isabela,NaN,31902.0,31902.0
42,San Manuel,17.0167,121.6333,Philippines,PH,Isabela,NaN,31896.0,31896.0
43,Cabarroguis,16.5833,121.5000,Philippines,PH,Quirino,admin,30582.0,30582.0
44,Mallig,17.2000,121.6167,Philippines,PH,Isabela,NaN,30459.0,30459.0
45,Buguey,18.2882,121.8331,Philippines,PH,Cagayan,minor,30175.0,30175.0
46,Claveria,18.6000,121.0833,Philippines,PH,Cagayan,NaN,29921.0,29921.0
47,Gamu,17.0500,121.8333,Philippines,PH,Isabela,NaN,29904.0,29904.0
48,Benito Soliven,16.9833,121.9500,Philippines,PH,Isabela,NaN,29624.0,29624.0
49,Iguig,17.7500,121.7333,Philippines,PH,Cagayan,NaN,27862.0,27862.0
50,Aglipay,16.4889,121.5874,Philippines,PH,Quirino,NaN,27787.0,27787.0
51,Dupax Del Norte,16.2864,121.0942,Philippines,PH,Nueva Vizcaya,NaN,27514.0,27514.0
52,Basco,20.4500,121.9667,Philippines,PH,Batanes,admin,8579.0,8579.0

In [22]:
# Save to csv
ph_cities_df.to_csv('ph_cities_filtered.csv', index=False)